---
#TODO
# - user management
# - backends / provisioning

- name: Ensure directories exist with needed permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0750
  with_items:
    - "{{ grafana_config_path }}"
    - "{{ grafana_db_path }}"

- name: "Make sure needed network exists"
  docker_network:
    name: "grafana"

- name: Create grafana instances
  include_tasks: create_instance.yml
  vars:
    grafana_instance: "{{ item.key }}"
    grafana_port: "{{ item.value }}"
    grafana_version: "{{ item.key }}"
    # Only this way dict keys with variables work
    grafana_labels: "{ 'traefik.enable':'true', 'traefik.http.routers.{{ item.key }}.rule':'Host(`{{ item.key }}.{{ grafana_url }}`)', 'traefik.http.services.{{ grafana_instance }}.loadbalancer.server.port':'3000', 'traefik.docker.network':'grafana' }"
  with_dict: "{{ grafana_instances }}"
