---
- hosts: grafana
  gather_facts: yes
  become: yes

  vars:
    # You can set proxy variables if needed here:
    #proxy_config:
    #  http_proxy: "http://my_proxy:port"
    #  https_proxy: "http://my_proxy:port"
    #  HTTP_PROXY: "my_proxy:port"
    #  HTTPS_PROXY: "my_proxy:port"
    #  NO_PROXY: "localhost,127.0.*"
    docker_install_compose: false
    grafana_url: "192.168.33.71.nip.io"
    grafana_instances:
      grafana01536: "version"
      grafana01536dev: "version"
      grafana01540: "version"
    grafana_admin_pass: "admin"

    #environment: "{{ proxy_config }}"

  #roles:
  #  - { role: docker }

  tasks:
    - name: "Rolle docker"
      include_role:
        name: docker
    - name: "Rolle traefik"
      include_role:
        name: traefik
    - name: "Rolle grafana"
      include_role:
        name: grafana

- hosts: remotes
  gather_facts: yes
  become: yes
 
  vars:
    grafana_ip: "192.168.33.71"
    grafana_url: "192.168.33.71.nip.io"
    mapping:
      node2: "grafana01536"
      #nodeX: "grafana01536dev"
      node3: "grafana01540"

  tasks:
    - name: "Rolle haproxy"
      include_role:
        name: haproxy
